question_data = [
    {"type": "boolean",
     "difficulty": "medium",
     "category": "General Knowledge",
     "question": "Furby was released in 1998.",
     "correct_answer": "True",
     "incorrect_answers": ["False"]},
    {"type": "boolean", "difficulty": "medium", "category": "General Knowledge",
     "question": "Francis Bacon died from a fatal case of pneumonia while he was attempting to preserve meat by stuffing a chicken with snow.", "correct_answer": "True",
     "incorrect_answers": ["False"]},
    {"type": "boolean", "difficulty": "medium", "category": "General Knowledge", "question": "The sum of all the numbers on a roulette wheel is 666.", "correct_answer": "True",
     "incorrect_answers": ["False"]},
    {"type": "boolean", "difficulty": "medium", "category": "General Knowledge", "question": "Pure water effectively conducts electricity ", "correct_answer": "False",
     "incorrect_answers": ["True"]},
    {"type": "boolean", "difficulty": "medium", "category": "General Knowledge", "question": "The scientific name for the Southern Lights is Aurora Australis?", "correct_answer": "True",
     "incorrect_answers": ["False"]},
    {"type": "boolean", "difficulty": "medium", "category": "General Knowledge", "question": "The Original Jack-o-Lanterns were actually hollowed out turnips.", "correct_answer": "True",
     "incorrect_answers": ["False"]},
    {"type": "boolean", "difficulty": "medium", "category": "General Knowledge", "question": "You are allowed to sell your soul on eBay.", "correct_answer": "False",
     "incorrect_answers": ["True"]},
    {"type": "boolean", "difficulty": "medium", "category": "General Knowledge", "question": "Coca-Cola&#039;s original colour was green.", "correct_answer": "False",
     "incorrect_answers": ["True"]},
    {"type": "boolean", "difficulty": "medium", "category": "General Knowledge", "question": "Ecuador uses the Mexican Peso as its currency.", "correct_answer": "False",
     "incorrect_answers": ["True"]},
    {"type": "boolean", "difficulty": "medium", "category": "General Knowledge", "question": "Instant mashed potatoes were invented by Canadian Edward Asselbergs in 1962.",
     "correct_answer": "True", "incorrect_answers": ["False"]},
    {"type": "boolean", "difficulty": "medium", "category": "General Knowledge", "question": "The Happy Face was created by commercial artist Harvey Ball.", "correct_answer": "True",
     "incorrect_answers": ["False"]},
    {"type": "boolean", "difficulty": "medium", "category": "General Knowledge", "question": "The US emergency hotline is 911 because of the September 11th terrorist attacks.",
     "correct_answer": "False", "incorrect_answers": ["True"]}, {"type": "boolean", "difficulty": "medium", "category": "General Knowledge",
                                                                 "question": "&quot;Typewriter&quot; is the longest word that can be typed using only the first row on a QWERTY keyboard.",
                                                                 "correct_answer": "False", "incorrect_answers": ["True"]},
    {"type": "boolean", "difficulty": "medium", "category": "General Knowledge", "question": "Don Cheto is the host of the radio station &quot;East Los FM&quot; in GTA V.",
     "correct_answer": "True", "incorrect_answers": ["False"]}, {"type": "boolean", "difficulty": "medium", "category": "General Knowledge",
                                                                 "question": "The word &quot;news&quot; originates from the first letters of the 4 main directions on a compass (North, East, West, South).",
                                                                 "correct_answer": "False", "incorrect_answers": ["True"]},
    {"type": "boolean", "difficulty": "medium", "category": "General Knowledge", "question": "Haggis is traditionally ate on Burns Night.", "correct_answer": "True",
     "incorrect_answers": ["False"]},
    {"type": "boolean", "difficulty": "medium", "category": "General Knowledge", "question": "An eggplant is a vegetable.", "correct_answer": "False", "incorrect_answers": ["True"]},
    {"type": "boolean", "difficulty": "medium", "category": "General Knowledge",
     "question": "SCP-173 was the first SCP article written for the web-based collaborative fiction project known as the &quot;SCP Foundation&quot;", "correct_answer": "True",
     "incorrect_answers": ["False"]},
    {"type": "boolean", "difficulty": "medium", "category": "General Knowledge", "question": "Cucumbers are usually more than 90% water.", "correct_answer": "True",
     "incorrect_answers": ["False"]},
    {"type": "boolean", "difficulty": "medium", "category": "General Knowledge", "question": "Only a small percentage of the world&#039;s population is lactose intolerant.",
     "correct_answer": "False", "incorrect_answers": ["True"]}
]
